services:
  producer:
    build: ../producer
    environment: { KAFKA_BROKERS: redpanda:9092 }
    networks: [grpc-pipeline]
    deploy:
      replicas: 2

  observability:
    build:
      context: ..
      dockerfile: ./observability/Dockerfile
    environment: {}
    ports:
      - "50051:50051"
    networks: [grpc-pipeline]

  processor:
    build:
      context: ..
      dockerfile: ./processor/Dockerfile
    environment: { KAFKA_BROKERS: redpanda:9092 }
    networks: [grpc-pipeline]
    depends_on: ["observability"]
    deploy:
      replicas: 4

  api:
    build: ../api
    environment: { PORT: "3000" }
    ports:
      - "3000:3000"
    networks: ["grpc-pipeline"]

networks:
  grpc-pipeline:
    external: true
