// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: observability.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  type Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  type Metadata,
  makeGenericClientConstructor,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "observability";

export interface TransactionMetricsRequest {
  statusCounts?: { [key: string]: number } | undefined;
  processorId?: string | undefined;
  timestampMs?: number | undefined;
}

export interface TransactionMetricsRequest_StatusCountsEntry {
  key: string;
  value: number;
}

export interface TransactionMetricsResponse {
  statusCounts?: { [key: string]: number } | undefined;
  totalProcessed?: number | undefined;
  lastUpdatedMs?: number | undefined;
}

export interface TransactionMetricsResponse_StatusCountsEntry {
  key: string;
  value: number;
}

export type Empty = {};

function createBaseTransactionMetricsRequest(): TransactionMetricsRequest {
  return { statusCounts: {}, processorId: "", timestampMs: 0 };
}

export const TransactionMetricsRequest: MessageFns<TransactionMetricsRequest> =
  {
    encode(
      message: TransactionMetricsRequest,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      globalThis.Object.entries(message.statusCounts || {}).forEach(
        ([key, value]: [string, number]) => {
          TransactionMetricsRequest_StatusCountsEntry.encode(
            { key: key as any, value },
            writer.uint32(10).fork(),
          ).join();
        },
      );
      if (message.processorId !== undefined && message.processorId !== "") {
        writer.uint32(18).string(message.processorId);
      }
      if (message.timestampMs !== undefined && message.timestampMs !== 0) {
        writer.uint32(24).int64(message.timestampMs);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): TransactionMetricsRequest {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransactionMetricsRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            const entry1 = TransactionMetricsRequest_StatusCountsEntry.decode(
              reader,
              reader.uint32(),
            );
            if (entry1.value !== undefined) {
              message.statusCounts![entry1.key] = entry1.value;
            }
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.processorId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.timestampMs = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): TransactionMetricsRequest {
      return {
        statusCounts: isObject(object.statusCounts)
          ? (
              globalThis.Object.entries(object.statusCounts) as [string, any][]
            ).reduce(
              (acc: { [key: string]: number }, [key, value]: [string, any]) => {
                acc[key] = globalThis.Number(value);
                return acc;
              },
              {},
            )
          : isObject(object.status_counts)
            ? (
                globalThis.Object.entries(object.status_counts) as [
                  string,
                  any,
                ][]
              ).reduce(
                (
                  acc: { [key: string]: number },
                  [key, value]: [string, any],
                ) => {
                  acc[key] = globalThis.Number(value);
                  return acc;
                },
                {},
              )
            : {},
        processorId: isSet(object.processorId)
          ? globalThis.String(object.processorId)
          : isSet(object.processor_id)
            ? globalThis.String(object.processor_id)
            : "",
        timestampMs: isSet(object.timestampMs)
          ? globalThis.Number(object.timestampMs)
          : isSet(object.timestamp_ms)
            ? globalThis.Number(object.timestamp_ms)
            : 0,
      };
    },

    toJSON(message: TransactionMetricsRequest): unknown {
      const obj: any = {};
      if (message.statusCounts) {
        const entries = globalThis.Object.entries(message.statusCounts) as [
          string,
          number,
        ][];
        if (entries.length > 0) {
          obj.statusCounts = {};
          entries.forEach(([k, v]) => {
            obj.statusCounts[k] = Math.round(v);
          });
        }
      }
      if (message.processorId !== undefined && message.processorId !== "") {
        obj.processorId = message.processorId;
      }
      if (message.timestampMs !== undefined && message.timestampMs !== 0) {
        obj.timestampMs = Math.round(message.timestampMs);
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<TransactionMetricsRequest>, I>>(
      base?: I,
    ): TransactionMetricsRequest {
      return TransactionMetricsRequest.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<TransactionMetricsRequest>, I>>(
      object: I,
    ): TransactionMetricsRequest {
      const message = createBaseTransactionMetricsRequest();
      message.statusCounts = (
        globalThis.Object.entries(object.statusCounts ?? {}) as [
          string,
          number,
        ][]
      ).reduce(
        (acc: { [key: string]: number }, [key, value]: [string, number]) => {
          if (value !== undefined) {
            acc[key] = globalThis.Number(value);
          }
          return acc;
        },
        {},
      );
      message.processorId = object.processorId ?? "";
      message.timestampMs = object.timestampMs ?? 0;
      return message;
    },
  };

function createBaseTransactionMetricsRequest_StatusCountsEntry(): TransactionMetricsRequest_StatusCountsEntry {
  return { key: "", value: 0 };
}

export const TransactionMetricsRequest_StatusCountsEntry: MessageFns<TransactionMetricsRequest_StatusCountsEntry> =
  {
    encode(
      message: TransactionMetricsRequest_StatusCountsEntry,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.key !== "") {
        writer.uint32(10).string(message.key);
      }
      if (message.value !== 0) {
        writer.uint32(16).int64(message.value);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): TransactionMetricsRequest_StatusCountsEntry {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransactionMetricsRequest_StatusCountsEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.value = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): TransactionMetricsRequest_StatusCountsEntry {
      return {
        key: isSet(object.key) ? globalThis.String(object.key) : "",
        value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      };
    },

    toJSON(message: TransactionMetricsRequest_StatusCountsEntry): unknown {
      const obj: any = {};
      if (message.key !== "") {
        obj.key = message.key;
      }
      if (message.value !== 0) {
        obj.value = Math.round(message.value);
      }
      return obj;
    },

    create<
      I extends Exact<
        DeepPartial<TransactionMetricsRequest_StatusCountsEntry>,
        I
      >,
    >(base?: I): TransactionMetricsRequest_StatusCountsEntry {
      return TransactionMetricsRequest_StatusCountsEntry.fromPartial(
        base ?? ({} as any),
      );
    },
    fromPartial<
      I extends Exact<
        DeepPartial<TransactionMetricsRequest_StatusCountsEntry>,
        I
      >,
    >(object: I): TransactionMetricsRequest_StatusCountsEntry {
      const message = createBaseTransactionMetricsRequest_StatusCountsEntry();
      message.key = object.key ?? "";
      message.value = object.value ?? 0;
      return message;
    },
  };

function createBaseTransactionMetricsResponse(): TransactionMetricsResponse {
  return { statusCounts: {}, totalProcessed: 0, lastUpdatedMs: 0 };
}

export const TransactionMetricsResponse: MessageFns<TransactionMetricsResponse> =
  {
    encode(
      message: TransactionMetricsResponse,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      globalThis.Object.entries(message.statusCounts || {}).forEach(
        ([key, value]: [string, number]) => {
          TransactionMetricsResponse_StatusCountsEntry.encode(
            { key: key as any, value },
            writer.uint32(10).fork(),
          ).join();
        },
      );
      if (
        message.totalProcessed !== undefined &&
        message.totalProcessed !== 0
      ) {
        writer.uint32(16).int64(message.totalProcessed);
      }
      if (message.lastUpdatedMs !== undefined && message.lastUpdatedMs !== 0) {
        writer.uint32(24).int64(message.lastUpdatedMs);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): TransactionMetricsResponse {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransactionMetricsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            const entry1 = TransactionMetricsResponse_StatusCountsEntry.decode(
              reader,
              reader.uint32(),
            );
            if (entry1.value !== undefined) {
              message.statusCounts![entry1.key] = entry1.value;
            }
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.totalProcessed = longToNumber(reader.int64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.lastUpdatedMs = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): TransactionMetricsResponse {
      return {
        statusCounts: isObject(object.statusCounts)
          ? (
              globalThis.Object.entries(object.statusCounts) as [string, any][]
            ).reduce(
              (acc: { [key: string]: number }, [key, value]: [string, any]) => {
                acc[key] = globalThis.Number(value);
                return acc;
              },
              {},
            )
          : isObject(object.status_counts)
            ? (
                globalThis.Object.entries(object.status_counts) as [
                  string,
                  any,
                ][]
              ).reduce(
                (
                  acc: { [key: string]: number },
                  [key, value]: [string, any],
                ) => {
                  acc[key] = globalThis.Number(value);
                  return acc;
                },
                {},
              )
            : {},
        totalProcessed: isSet(object.totalProcessed)
          ? globalThis.Number(object.totalProcessed)
          : isSet(object.total_processed)
            ? globalThis.Number(object.total_processed)
            : 0,
        lastUpdatedMs: isSet(object.lastUpdatedMs)
          ? globalThis.Number(object.lastUpdatedMs)
          : isSet(object.last_updated_ms)
            ? globalThis.Number(object.last_updated_ms)
            : 0,
      };
    },

    toJSON(message: TransactionMetricsResponse): unknown {
      const obj: any = {};
      if (message.statusCounts) {
        const entries = globalThis.Object.entries(message.statusCounts) as [
          string,
          number,
        ][];
        if (entries.length > 0) {
          obj.statusCounts = {};
          entries.forEach(([k, v]) => {
            obj.statusCounts[k] = Math.round(v);
          });
        }
      }
      if (
        message.totalProcessed !== undefined &&
        message.totalProcessed !== 0
      ) {
        obj.totalProcessed = Math.round(message.totalProcessed);
      }
      if (message.lastUpdatedMs !== undefined && message.lastUpdatedMs !== 0) {
        obj.lastUpdatedMs = Math.round(message.lastUpdatedMs);
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<TransactionMetricsResponse>, I>>(
      base?: I,
    ): TransactionMetricsResponse {
      return TransactionMetricsResponse.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<TransactionMetricsResponse>, I>>(
      object: I,
    ): TransactionMetricsResponse {
      const message = createBaseTransactionMetricsResponse();
      message.statusCounts = (
        globalThis.Object.entries(object.statusCounts ?? {}) as [
          string,
          number,
        ][]
      ).reduce(
        (acc: { [key: string]: number }, [key, value]: [string, number]) => {
          if (value !== undefined) {
            acc[key] = globalThis.Number(value);
          }
          return acc;
        },
        {},
      );
      message.totalProcessed = object.totalProcessed ?? 0;
      message.lastUpdatedMs = object.lastUpdatedMs ?? 0;
      return message;
    },
  };

function createBaseTransactionMetricsResponse_StatusCountsEntry(): TransactionMetricsResponse_StatusCountsEntry {
  return { key: "", value: 0 };
}

export const TransactionMetricsResponse_StatusCountsEntry: MessageFns<TransactionMetricsResponse_StatusCountsEntry> =
  {
    encode(
      message: TransactionMetricsResponse_StatusCountsEntry,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.key !== "") {
        writer.uint32(10).string(message.key);
      }
      if (message.value !== 0) {
        writer.uint32(16).int64(message.value);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): TransactionMetricsResponse_StatusCountsEntry {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransactionMetricsResponse_StatusCountsEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.value = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): TransactionMetricsResponse_StatusCountsEntry {
      return {
        key: isSet(object.key) ? globalThis.String(object.key) : "",
        value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      };
    },

    toJSON(message: TransactionMetricsResponse_StatusCountsEntry): unknown {
      const obj: any = {};
      if (message.key !== "") {
        obj.key = message.key;
      }
      if (message.value !== 0) {
        obj.value = Math.round(message.value);
      }
      return obj;
    },

    create<
      I extends Exact<
        DeepPartial<TransactionMetricsResponse_StatusCountsEntry>,
        I
      >,
    >(base?: I): TransactionMetricsResponse_StatusCountsEntry {
      return TransactionMetricsResponse_StatusCountsEntry.fromPartial(
        base ?? ({} as any),
      );
    },
    fromPartial<
      I extends Exact<
        DeepPartial<TransactionMetricsResponse_StatusCountsEntry>,
        I
      >,
    >(object: I): TransactionMetricsResponse_StatusCountsEntry {
      const message = createBaseTransactionMetricsResponse_StatusCountsEntry();
      message.key = object.key ?? "";
      message.value = object.value ?? 0;
      return message;
    },
  };

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

export type ObservabilityServiceService = typeof ObservabilityServiceService;
export const ObservabilityServiceService = {
  /** Processor pushes aggregated transaction metrics */
  recordTransactionMetrics: {
    path: "/observability.ObservabilityService/RecordTransactionMetrics" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TransactionMetricsRequest): Buffer =>
      Buffer.from(TransactionMetricsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TransactionMetricsRequest =>
      TransactionMetricsRequest.decode(value),
    responseSerialize: (value: Empty): Buffer =>
      Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  getTransactionMetrics: {
    path: "/observability.ObservabilityService/GetTransactionMetrics" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: Empty): Buffer =>
      Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: TransactionMetricsResponse): Buffer =>
      Buffer.from(TransactionMetricsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TransactionMetricsResponse =>
      TransactionMetricsResponse.decode(value),
  },
} as const;

export interface ObservabilityServiceServer extends UntypedServiceImplementation {
  /** Processor pushes aggregated transaction metrics */
  recordTransactionMetrics: handleUnaryCall<TransactionMetricsRequest, Empty>;
  getTransactionMetrics: handleUnaryCall<Empty, TransactionMetricsResponse>;
}

export interface ObservabilityServiceClient extends Client {
  /** Processor pushes aggregated transaction metrics */
  recordTransactionMetrics(
    request: TransactionMetricsRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  recordTransactionMetrics(
    request: TransactionMetricsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  recordTransactionMetrics(
    request: TransactionMetricsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  getTransactionMetrics(
    request: Empty,
    callback: (
      error: ServiceError | null,
      response: TransactionMetricsResponse,
    ) => void,
  ): ClientUnaryCall;
  getTransactionMetrics(
    request: Empty,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: TransactionMetricsResponse,
    ) => void,
  ): ClientUnaryCall;
  getTransactionMetrics(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: TransactionMetricsResponse,
    ) => void,
  ): ClientUnaryCall;
}

export const ObservabilityServiceClient = makeGenericClientConstructor(
  ObservabilityServiceService,
  "observability.ObservabilityService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): ObservabilityServiceClient;
  service: typeof ObservabilityServiceService;
  serviceName: string;
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
