// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: observability.proto

package observability

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservabilityService_RecordTransactionMetrics_FullMethodName = "/observability.ObservabilityService/RecordTransactionMetrics"
	ObservabilityService_GetTransactionMetrics_FullMethodName    = "/observability.ObservabilityService/GetTransactionMetrics"
)

// ObservabilityServiceClient is the client API for ObservabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObservabilityServiceClient interface {
	// Processor pushes aggregated transaction metrics
	RecordTransactionMetrics(ctx context.Context, in *TransactionMetricsRequest, opts ...grpc.CallOption) (*Empty, error)
	GetTransactionMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransactionMetricsResponse, error)
}

type observabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservabilityServiceClient(cc grpc.ClientConnInterface) ObservabilityServiceClient {
	return &observabilityServiceClient{cc}
}

func (c *observabilityServiceClient) RecordTransactionMetrics(ctx context.Context, in *TransactionMetricsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ObservabilityService_RecordTransactionMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observabilityServiceClient) GetTransactionMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransactionMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionMetricsResponse)
	err := c.cc.Invoke(ctx, ObservabilityService_GetTransactionMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservabilityServiceServer is the server API for ObservabilityService service.
// All implementations must embed UnimplementedObservabilityServiceServer
// for forward compatibility.
type ObservabilityServiceServer interface {
	// Processor pushes aggregated transaction metrics
	RecordTransactionMetrics(context.Context, *TransactionMetricsRequest) (*Empty, error)
	GetTransactionMetrics(context.Context, *Empty) (*TransactionMetricsResponse, error)
	mustEmbedUnimplementedObservabilityServiceServer()
}

// UnimplementedObservabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservabilityServiceServer struct{}

func (UnimplementedObservabilityServiceServer) RecordTransactionMetrics(context.Context, *TransactionMetricsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordTransactionMetrics not implemented")
}
func (UnimplementedObservabilityServiceServer) GetTransactionMetrics(context.Context, *Empty) (*TransactionMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionMetrics not implemented")
}
func (UnimplementedObservabilityServiceServer) mustEmbedUnimplementedObservabilityServiceServer() {}
func (UnimplementedObservabilityServiceServer) testEmbeddedByValue()                              {}

// UnsafeObservabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservabilityServiceServer will
// result in compilation errors.
type UnsafeObservabilityServiceServer interface {
	mustEmbedUnimplementedObservabilityServiceServer()
}

func RegisterObservabilityServiceServer(s grpc.ServiceRegistrar, srv ObservabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedObservabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservabilityService_ServiceDesc, srv)
}

func _ObservabilityService_RecordTransactionMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).RecordTransactionMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_RecordTransactionMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).RecordTransactionMetrics(ctx, req.(*TransactionMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservabilityService_GetTransactionMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).GetTransactionMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_GetTransactionMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).GetTransactionMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ObservabilityService_ServiceDesc is the grpc.ServiceDesc for ObservabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "observability.ObservabilityService",
	HandlerType: (*ObservabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordTransactionMetrics",
			Handler:    _ObservabilityService_RecordTransactionMetrics_Handler,
		},
		{
			MethodName: "GetTransactionMetrics",
			Handler:    _ObservabilityService_GetTransactionMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "observability.proto",
}
