// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: observability.proto

package observability

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCounts  map[string]int64       `protobuf:"bytes,1,rep,name=status_counts,json=statusCounts,proto3" json:"status_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ProcessorId   string                 `protobuf:"bytes,2,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMetricsRequest) Reset() {
	*x = TransactionMetricsRequest{}
	mi := &file_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMetricsRequest) ProtoMessage() {}

func (x *TransactionMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMetricsRequest.ProtoReflect.Descriptor instead.
func (*TransactionMetricsRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionMetricsRequest) GetStatusCounts() map[string]int64 {
	if x != nil {
		return x.StatusCounts
	}
	return nil
}

func (x *TransactionMetricsRequest) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *TransactionMetricsRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type TransactionMetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StatusCounts   map[string]int64       `protobuf:"bytes,1,rep,name=status_counts,json=statusCounts,proto3" json:"status_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TotalProcessed int64                  `protobuf:"varint,2,opt,name=total_processed,json=totalProcessed,proto3" json:"total_processed,omitempty"`
	LastUpdatedMs  int64                  `protobuf:"varint,3,opt,name=last_updated_ms,json=lastUpdatedMs,proto3" json:"last_updated_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionMetricsResponse) Reset() {
	*x = TransactionMetricsResponse{}
	mi := &file_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMetricsResponse) ProtoMessage() {}

func (x *TransactionMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMetricsResponse.ProtoReflect.Descriptor instead.
func (*TransactionMetricsResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionMetricsResponse) GetStatusCounts() map[string]int64 {
	if x != nil {
		return x.StatusCounts
	}
	return nil
}

func (x *TransactionMetricsResponse) GetTotalProcessed() int64 {
	if x != nil {
		return x.TotalProcessed
	}
	return 0
}

func (x *TransactionMetricsResponse) GetLastUpdatedMs() int64 {
	if x != nil {
		return x.LastUpdatedMs
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_observability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{2}
}

var File_observability_proto protoreflect.FileDescriptor

const file_observability_proto_rawDesc = "" +
	"\n" +
	"\x13observability.proto\x12\robservability\"\x83\x02\n" +
	"\x19TransactionMetricsRequest\x12_\n" +
	"\rstatus_counts\x18\x01 \x03(\v2:.observability.TransactionMetricsRequest.StatusCountsEntryR\fstatusCounts\x12!\n" +
	"\fprocessor_id\x18\x02 \x01(\tR\vprocessorId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x1a?\n" +
	"\x11StatusCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x90\x02\n" +
	"\x1aTransactionMetricsResponse\x12`\n" +
	"\rstatus_counts\x18\x01 \x03(\v2;.observability.TransactionMetricsResponse.StatusCountsEntryR\fstatusCounts\x12'\n" +
	"\x0ftotal_processed\x18\x02 \x01(\x03R\x0etotalProcessed\x12&\n" +
	"\x0flast_updated_ms\x18\x03 \x01(\x03R\rlastUpdatedMs\x1a?\n" +
	"\x11StatusCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\a\n" +
	"\x05Empty2\xcc\x01\n" +
	"\x14ObservabilityService\x12Z\n" +
	"\x18RecordTransactionMetrics\x12(.observability.TransactionMetricsRequest\x1a\x14.observability.Empty\x12X\n" +
	"\x15GetTransactionMetrics\x12\x14.observability.Empty\x1a).observability.TransactionMetricsResponseB?Z=github.com/femitubosun/streaming-pipeline/proto/observabilityb\x06proto3"

var (
	file_observability_proto_rawDescOnce sync.Once
	file_observability_proto_rawDescData []byte
)

func file_observability_proto_rawDescGZIP() []byte {
	file_observability_proto_rawDescOnce.Do(func() {
		file_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observability_proto_rawDesc), len(file_observability_proto_rawDesc)))
	})
	return file_observability_proto_rawDescData
}

var file_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_observability_proto_goTypes = []any{
	(*TransactionMetricsRequest)(nil),  // 0: observability.TransactionMetricsRequest
	(*TransactionMetricsResponse)(nil), // 1: observability.TransactionMetricsResponse
	(*Empty)(nil),                      // 2: observability.Empty
	nil,                                // 3: observability.TransactionMetricsRequest.StatusCountsEntry
	nil,                                // 4: observability.TransactionMetricsResponse.StatusCountsEntry
}
var file_observability_proto_depIdxs = []int32{
	3, // 0: observability.TransactionMetricsRequest.status_counts:type_name -> observability.TransactionMetricsRequest.StatusCountsEntry
	4, // 1: observability.TransactionMetricsResponse.status_counts:type_name -> observability.TransactionMetricsResponse.StatusCountsEntry
	0, // 2: observability.ObservabilityService.RecordTransactionMetrics:input_type -> observability.TransactionMetricsRequest
	2, // 3: observability.ObservabilityService.GetTransactionMetrics:input_type -> observability.Empty
	2, // 4: observability.ObservabilityService.RecordTransactionMetrics:output_type -> observability.Empty
	1, // 5: observability.ObservabilityService.GetTransactionMetrics:output_type -> observability.TransactionMetricsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_observability_proto_init() }
func file_observability_proto_init() {
	if File_observability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observability_proto_rawDesc), len(file_observability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_observability_proto_goTypes,
		DependencyIndexes: file_observability_proto_depIdxs,
		MessageInfos:      file_observability_proto_msgTypes,
	}.Build()
	File_observability_proto = out.File
	file_observability_proto_goTypes = nil
	file_observability_proto_depIdxs = nil
}
